### ISSUE TITLE
There already is a project for University SSO Django called "Uniauth" that predates yours by two years

### ISSUE THREAD

**Issue by jlumbroso** [UniversitaDellaCalabria/uniAuth#22]
I just want to attract your attention to the fact that there is an existing, open-source project called Uniauth, of which the goal is exactly what you are doing:

https://github.com/lgoodridge/django-uniauth

I am very confused as to why you would create a completely new project, rather than integrate pysaml2 to this existing project.

Is it just a problem of NIH?

**Comment by peppelinux** [comment]
Hi Jeremie,

The Name of our Organization is Unical and that name sounds good to us. 
Lately I found that there was another project but, formerly, django-uniauth is a app and uniAuth is a complete SAML2 IdP.

Also in our context CAS is deprecated.
Soon as possible uniAuth will integrate a OIDC Provider (django-oidc-op).

Sorry for this name collition, mea culpa ;)

**Comment by jlumbroso** [comment]
@peppelinux Gracie mille for your kind reply :)

These are things that happen! Though it makes me happy to know you will eventually integrate with OIDC Provider.
