### ISSUE TITLE
LDAPSocketOpenError even after disabling ldap

### ISSUE THREAD

**Issue by omizrahi99** [UniversitaDellaCalabria/uniAuth#27]
## Code Version

Master Branch

## Expected Behavior

There shouldn't be an LDAP error when LDAP is specified to be disabled.

## Current Behavior

When logging in from an SP (while 'ldap_peoples' and 'multildap' are removed from INSTALLED_APPS in django_idp/settingslocal.py), I get an LDAPSocketOpenError from the IdP.

## Possible Solution

I solved this by commenting out all the code under `# pyMultiLDAP related` in `settingslocal.py`. Doing this gave me an error that `LDAP_CONNECTIONS` has no attribute, so I just set `LDAP_CONNECTIONS = {}` to get around this. After, I was able to log in using a test SP.

A permanent solution might be to refrain from running all LDAP-related code when `ldap_peoples` and `multildap` are disabled.

## Steps to Reproduce

1. Set up `django_idp` using the documentation, and add a test SP to test login.
2. Remove `ldap_peoples` and `multildap` from `INSTALLED_APPS` in `django_idp/settingslocal.py`
3. Try logging in from SP, and see the `LDAPSocketOpenError` in the CLI and IdP UI.

**Comment by peppelinux** [comment]
See default SP processor or what you degined in SP configuration (/admin)

By default, in settingslocal, it's configured to

https://github.com/UniversitaDellaCalabria/uniAuth/blob/be33d3be10f82e955deffe7ad4b34eeafca4195a/django_idp/idp_pysaml2.py.example#L264

You can use the base processor or whatever inherited from it

**Comment by peppelinux** [comment]
BaseProcessor, the simplest one, It rely on Django user accounts

https://github.com/UniversitaDellaCalabria/uniAuth/blob/19ffcbe9217e7aa8b38ee6cde8f3a8ad1480dbb2/uniauth/processors.py#L108

**Comment by peppelinux** [comment]
That's something similar of what you have once a SP being accepted by uniAuth (its EntityID Is in pysaml2 metadastore)

https://github.com/UniversitaDellaCalabria/uniAuth/blob/master/documentation/contents/sp.png

If you disabile automatic registration on SP you Will have to configure It by Hand

See also ./manage.py mdquery and aacli commands, they are quite helpfull to test so and user attributes without doping any real http request

**Comment by peppelinux** [comment]
I got It.
settingslocal.py Is something that must be customized by user, however I'll reproduce this issue to male a Better decision about how would be a good solution to that.

We could Simply put a if statement to prrvent LDAP related patameters to be loaded.

```
if 'multildap' in INSTALLED_APPS:
   ...
```

hopefilly It would be a good example to put in

**Comment by peppelinux** [comment]
done here:
https://github.com/UniversitaDellaCalabria/uniAuth/commit/025789a4569a58934eb98edae6ae35ab8774ff0f#diff-63163e085908a60002123b630032eaf7d67b4b120025b996b88a276ed361d306R131
