### ISSUE TITLE
NameIdBuilder.get_nameid_unspecified() is missing **kwargs in function parameters

### ISSUE THREAD

**Issue by omizrahi99** [UniversitaDellaCalabria/uniAuth#28]
When [this function](https://github.com/UniversitaDellaCalabria/uniAuth/blob/19ffcbe9217e7aa8b38ee6cde8f3a8ad1480dbb2/uniauth/processors.py#L150) calls `get_nameid_unspecified()`, it is currently passing in too many arguments for `get_nameid_unspecified()` to process.

A solution would be to add `**kwargs` as a parameter to the definition of `get_nameid_unspecified()` [here](https://github.com/UniversitaDellaCalabria/uniAuth/blob/19ffcbe9217e7aa8b38ee6cde8f3a8ad1480dbb2/uniauth/processors.py#L90).

I found out about this bug when I was trying to log in to a service provider that was asking for the unspecified nameid format.

**Comment by peppelinux** [comment]
That's good!
The unspecified nameid format was not covered yet, feel free to put your proposed patch with a PR in the Dev branch, I'll merge It asap
