### ISSUE TITLE
adfs 2019

### ISSUE THREAD

**Issue by santosshen** [UniversitaDellaCalabria/uniAuth#34]
adfs 2019
python 3.6
uniAuth 

Tutorial on using uniauth in ADFs 2019
[FederationMetadata.zip](https://github.com/UniversitaDellaCalabria/uniAuth/files/6220953/FederationMetadata.zip)
Based on this metadatastore generation idp.xml
![image](https://user-images.githubusercontent.com/25058112/112822338-63f13100-90ba-11eb-9d75-e39bebbc4c3a.png)

![image](https://user-images.githubusercontent.com/25058112/112822381-723f4d00-90ba-11eb-9b1e-b8da65327fbe.png)

**Comment by peppelinux** [comment]
is it working or is there something wrong with that?

**Comment by santosshen** [comment]
adfs2019 + uniauth file  
I have encountered a mistake. The official website document only has simple pictures

![image](https://user-images.githubusercontent.com/25058112/112854873-dc6ae880-90e0-11eb-80cd-ca81a79b6c65.png)
Storage adfs is not valid, if 'mdq' at least a valid url must be inserted. If local: at least a file or a valid path. Endpoint is not reachable: HTTPSConnectionPool(host='adfs1.testyunwei.com', port=8088): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f994601d048>: Failed to establish a new connection: [Errno 111] Connection refused',))

adfs1.testyunwei.com is localhost

![image](https://user-images.githubusercontent.com/25058112/112855031-06240f80-90e1-11eb-9684-60bf36594ddf.png)

**Comment by peppelinux** [comment]
don't use remote if you have a local file on storage,
just this

and more, I suggest you to put only a folder as url, a local relative or an absolute path to the directory that contains all the metadata

**Comment by santosshen** [comment]
![image](https://user-images.githubusercontent.com/25058112/112921697-d2c39e00-913d-11eb-8e89-94d8bda5a024.png)
is not present in any Metadata

**Comment by peppelinux** [comment]
the metadatadata store:
change remote to local

then check your metadata, is there that entityid in it?

**Comment by peppelinux** [comment]
Is this time to close this issue, did you have fixed this problem?
